apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db
      app.kubernetes.io/name: mysql
  serviceName: "auth-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-db
        app.kubernetes.io/name: mysql
    spec:
      containers:
      - name: auth-db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-auth-vol
          mountPath: /var/lib/mysql
          subPath: mysql
        envFrom:
        - configMapRef:
            name: db-env
        - secretRef:
            name: db-credentials
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
          limits:
            cpu: 50m
            memory: 400Mi
      volumes:
      - name: mysql-auth-vol
        persistentVolumeClaim:
          claimName: mysql-auth-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    app: auth-db
    app.kubernetes.io/name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: auth-db