apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db
  serviceName: "auth-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: auth-db
        image: mysql:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-auth-vol
          mountPath: /data/db
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: MYSQL_USER
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: MYSQL_PASSWORD
      volumes:
      - name: mysql-auth-vol
        persistentVolumeClaim:
          claimName: mysql-auth-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: auth-db