apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-ms-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmark-ms
  template:
    metadata:
      labels:
        app: bookmark-ms
    spec:
      containers:
      - name: bookmark-ms
        image: ywonchae1/stopbang-bookmark-ms
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ms-env
        - secretRef:
            name: ms-credentials
        resources:
          requests:
            cpu: 1m
          limits:
            cpu: 5m

---
apiVersion: v1
kind: Service
metadata:
  name: bookmark-ms
spec:
  ports:
  - port: 3000
  selector:
    app: bookmark-ms

