version: '3'
services:

  stop_bang_main:
    image: stop_bang_main
    build:
      context: ./stop_bang_main
      dockerfile: Dockerfile
    container_name: stop_bang_main
    ports:
      - '3000:3000'
    env_file: ./stop_bang_main/.env
    restart: 'no'
  
  stop_bang_register:
    image: stop_bang_register
    build:
      context: ./stop_bang_register
      dockerfile: Dockerfile
    container_name: stop_bang_register
    env_file: ./stop_bang_register/.env
    restart: 'no'

  stop_bang_login_logout:
    image: stop_bang_login_logout
    build:
      context: ./stop_bang_login_logout
      dockerfile: Dockerfile
    container_name: stop_bang_login_logout
    env_file: ./stop_bang_login_logout/.env
    restart: 'no'
  
  stop_bang_resident_mypage:
    image: stop_bang_resident_mypage
    build:
      context: ./stop_bang_resident_mypage
      dockerfile: Dockerfile
    container_name: stop_bang_resident_mypage
    env_file: ./stop_bang_resident_mypage/.env
    restart: 'no'

  stop_bang_realtor_page:
    image: stop_bang_realtor_page
    build:
      context: ./stop_bang_realtor_page
      dockerfile: Dockerfile
    container_name: stop_bang_realtor_page
    env_file: ./stop_bang_realtor_page/.env
    restart: 'no'

  stop_bang_agent_mypage:
    image: stop_bang_agent_mypage
    build:
      context: ./stop_bang_agent_mypage
      dockerfile: Dockerfile
    container_name: stop_bang_agent_mypage
    env_file: ./stop_bang_agent_mypage/.env
    restart: 'no'

  stop_bang_bookmark:
    image: stop_bang_bookmark
    build:
      context: ./stop_bang_bookmark
      dockerfile: Dockerfile
    container_name: stop_bang_bookmark
    env_file: ./stop_bang_bookmark/.env
    restart: 'no'

  stop_bang_map:
    image: stop_bang_map
    build:
      context: ./stop_bang_map
      dockerfile: Dockerfile
    container_name: stop_bang_map
    env_file: ./stop_bang_map/.env
    restart: 'no'
    
# DB 관련 마이크로서비스
  stop_bang_sub_feature_DB:
    image: stop_bang_sub_feature_db
    build:
      context: ./stop_bang_sub_feature_DB
      dockerfile: Dockerfile
    container_name: stop_bang_sub_feature_db
    env_file: ./stop_bang_sub_feature_DB/.env
    restart: 'no'

  stop_bang_auth_DB:
    image: stop_bang_auth_db
    build:
      context: ./stop_bang_auth_DB
      dockerfile: Dockerfile
    container_name: stop_bang_auth_db
    restart: no
    depends_on:
      - 'auth_db'

  stop_bang_review_DB:
    image: stop_bang_review_db
    build:
      context: ./stop_bang_review_DB
      dockerfile: Dockerfile
    container_name: stop_bang_review_DB
    restart: no
    depends_on:
      - 'review_db'

  auth_db:
    image: mysql
    container_name: auth_db
    env_file: ./.env_auth_db
    restart: 'no'

  sub_db:
    image: mysql
    container_name: sub_db
    env_file: ./.env_auth_db
    volumes:
      - ./sub_db_init:/docker-entrypoint-initdb.d
    restart: 'no'

  review_db:
    image: mysql
    container_name: review_db
    env_file: ./.env_auth_db
    restart: 'no'