version: '3'
services:

  stop_bang_main:
    image: stop_bang_main
    build:
      context: ./stop_bang_main
      dockerfile: Dockerfile
    container_name: stop_bang_main
    ports:
      - '3000:3000'
    env_file: ./stop_bang_main/.env
    restart: 'no'
  
  stop_bang_login_logout:
    image: stop_bang_login_logout
    build:
      context: ./stop_bang_login_logout
      dockerfile: Dockerfile
    container_name: stop_bang_login_logout
    env_file: ./stop_bang_login_logout/.env
    restart: 'no'
  
  stop_bang_resident_mypage:
    image: stop_bang_resident_mypage
    build:
      context: ./stop_bang_resident_mypage
      dockerfile: Dockerfile
    container_name: stop_bang_resident_mypage
    env_file: ./stop_bang_resident_mypage/.env
    restart: 'no'

  stop_bang_sub_feature_DB:
    image: stop_bang_sub_feature_db
    build:
      context: ./stop_bang_sub_feature_DB
      dockerfile: Dockerfile
    container_name: stop_bang_sub_feature_db
    env_file: ./stop_bang_sub_feature_DB/.env
    restart: 'no'