version: '3'
services:

  stop_bang_main:
    image: stop_bang_main
    build:
      context: ./stop_bang_main
      dockerfile: Dockerfile
    container_name: stop_bang_main
    ports:
      - '3000:3000'
    env_file: ./stop_bang_main/.env
    restart: 'no'
  
  stop_bang_login_logout:
    image: stop_bang_login_logout
    build:
      context: ./stop_bang_login_logout
      dockerfile: Dockerfile
    container_name: stop_bang_login_logout
    env_file: ./stop_bang_login_logout/.env
    restart: 'no'