apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-ms-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-ms
  template:
    metadata:
      labels:
        app: main-ms
    spec:
      containers:
      - name: main-ms
        image: ywonchae1/stopbang-main-ms
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ms-env
        - secretRef:
            name: ms-credentials
        env:
        - name: MS_PORT
          value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: main-ms
spec:
  type: LoadBalancer
  loadBalancerIP: 34.47.66.50
  ports:
  - port: 3000
    # targetPort: 3000
  selector:
    app: main-ms

