apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: main-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-ms-deploy
  minReplicas: 1
  maxReplicas: 14
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60