apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-ms-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-ms
  template:
    metadata:
      labels:
        app: review-ms
    spec:
      containers:
      - name: review-ms
        image: ywonchae1/stopbang-review-ms
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ms-env
        - secretRef:
            name: ms-credentials
        resources:
          requests:
            cpu: 1m
            memory: 15Mi
          limits:
            cpu: 10m
            memory: 30Mi

---
apiVersion: v1
kind: Service
metadata:
  name: review-ms
spec:
  ports:
  - port: 3000
  selector:
    app: review-ms

