apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-review-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: review-db
spec:
  selector:
    matchLabels:
      app: review-db
      app.kubernetes.io/name: mysql
  serviceName: "review-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: review-db
        app.kubernetes.io/name: mysql
    spec:
      containers:
      - name: review-db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-review-vol
          mountPath: /var/lib/mysql
          subPath: mysql
        envFrom:
        - configMapRef:
            name: db-env
        - secretRef:
            name: db-credentials
        resources:
          requests:
            cpu: 1m
            memory: 195Mi
          limits:
            cpu: 20m
            memory: 300Mi
      volumes:
      - name: mysql-review-vol
        persistentVolumeClaim:
          claimName: mysql-review-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: review-db
  labels:
    app: review-db
    app.kubernetes.io/name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: review-db