apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-api
  template:
    metadata:
      labels:
        app: review-api
    spec:
      initContainers:
      - name: wait-for-review-db
        image: busybox
        command: ['sh', '-c', 'until nc -z review-db 3306; do echo waiting for review-db; sleep 2; done;']
      containers:
      - name: review-api
        image: bibicsh22/stopbang-review-api
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: review-api-env
        - secretRef:
            name: review-api-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: review-api
spec:
  ports:
  - port: 3000
  selector:
    app: review-api

