apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub-api
  template:
    metadata:
      labels:
        app: sub-api
    spec:
      containers:
      - name: sub-api
        image: ywonchae1/stopbang-sub-api
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: sub-api-env
        - secretRef:
            name: sub-api-credentials
        env:
        - name: RABBIT
          value: amqp://rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: sub-api
spec:
  ports:
  - port: 3000
  selector:
    app: sub-api

