apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-sub-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sub-db
spec:
  selector:
    matchLabels:
      app: sub-db
      app.kubernetes.io/name: mysql
  serviceName: "sub-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: sub-db
        app.kubernetes.io/name: mysql
    spec:
      containers:
      - name: sub-db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-sub-vol
          mountPath: /var/lib/mysql
          subPath: mysql
        envFrom:
        - configMapRef:
            name: db-env
        envFrom:
        - secretRef:
            name: db-credentials
      volumes:
      - name: mysql-sub-vol
        persistentVolumeClaim:
          claimName: mysql-sub-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sub-db
  labels:
    app: sub-db
    app.kubernetes.io/name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: sub-db